"""Deterministic, local-only MP4 vertical-slice production helpers."""

from .runtime import (
    PRODUCTION_SLICE_SCHEMA_VERSION,
    build_render,
    build_storyboard,
    build_subtitles,
    initialize_production,
    verify_render,
)
from .documentary_v2 import (
    build_documentary_v2_render,
    build_documentary_v2_storyboard,
    build_documentary_v2_subtitles,
    initialize_documentary_v2,
    verify_documentary_v2_render,
)
from .documentary_v3 import (
    DocumentaryV3Config,
    build_documentary_v3_assets,
    build_documentary_v3_render,
    build_documentary_v3_subtitles,
    initialize_documentary_v3,
    verify_documentary_v3_render,
)
from .neural_voice import (
    AZURE_NEURAL_PROVIDER,
    AzureNeuralArabicVoiceProvider,
    AzureNeuralVoiceConfig,
    AzureSpeechSDKArabicVoiceProvider,
    NeuralVoiceError,
    NeuralVoiceRequest,
    NeuralVoiceResult,
    run_azure_voice_audition_gate,
    run_azure_bassel_diagnostic,
    validate_wav_audio,
)
from .quality_gate_v4 import (
    CuratedGeneratedVisualProvider,
    VisualAssetSpec,
    VoiceProviderSelection,
    VoiceProviderRegistry,
    build_visual_auditions,
    create_quality_gate_voice_selection,
)
from .quality_gate_render_v4 import build_quality_gate_v4
from .audio_mastering_v1 import (
    AUDIO_MASTERING_REPORT_SCHEMA_V1,
    AudioMasteringResult,
    analyze_loudness,
    master_audio,
    verify_loudness,
)
from .diagnostic_voice_provider_v1 import (
    DIAGNOSTIC_VOICE_PROVIDER_ID,
    DiagnosticToneVoiceProvider,
    write_diagnostic_wav,
)
from .voice_provider_v1 import (
    VOICE_REPORT_SCHEMA_V1,
    VOICE_REQUEST_SCHEMA_V1,
    VoiceProvider,
    VoiceSegment,
    VoiceSynthesisResult,
    build_voice_segments,
    estimate_arabic_duration_ms,
    normalize_arabic_text,
    split_arabic_narration,
    validate_voice_request,
)
from .render_adapter_v2 import (
    EpisodeRenderAdapterV2,
    EpisodeRenderV2Result,
    RENDER_ADAPTER_V2_REPORT_SCHEMA,
    render_episode_manifest_v2,
)
from .render_adapter_v1 import (
    RENDER_ADAPTER_SCHEMA_VERSION,
    LocalVideoRenderAdapter,
    LocalVideoRenderResult,
    render_local_video_manifest,
)
from .episode_preproduction_v4 import build_episode_01_preproduction
from .episode_render_v2 import (
    EPISODE_RENDER_MANIFEST_V2,
    TimedScene,
    build_timed_scene_plan,
    validate_episode_render_manifest_v2,
)

__all__ = [
    "PRODUCTION_SLICE_SCHEMA_VERSION",
    "build_render",
    "build_storyboard",
    "build_subtitles",
    "initialize_production",
    "verify_render",
    "build_documentary_v2_render",
    "build_documentary_v2_storyboard",
    "build_documentary_v2_subtitles",
    "initialize_documentary_v2",
    "verify_documentary_v2_render",
    "build_documentary_v3_assets",
    "DocumentaryV3Config",
    "build_documentary_v3_render",
    "build_documentary_v3_subtitles",
    "initialize_documentary_v3",
    "verify_documentary_v3_render",
    "AZURE_NEURAL_PROVIDER",
    "AzureNeuralArabicVoiceProvider",
    "AzureNeuralVoiceConfig",
    "AzureSpeechSDKArabicVoiceProvider",
    "NeuralVoiceError",
    "NeuralVoiceRequest",
    "NeuralVoiceResult",
    "run_azure_voice_audition_gate",
    "run_azure_bassel_diagnostic",
    "validate_wav_audio",
    "CuratedGeneratedVisualProvider",
    "VisualAssetSpec",
    "VoiceProviderSelection",
    "VoiceProviderRegistry",
    "build_visual_auditions",
    "create_quality_gate_voice_selection",
    "build_quality_gate_v4",
    "RENDER_ADAPTER_SCHEMA_VERSION",
    "AUDIO_MASTERING_REPORT_SCHEMA_V1",
    "AudioMasteringResult",
    "analyze_loudness",
    "master_audio",
    "verify_loudness",
    "DIAGNOSTIC_VOICE_PROVIDER_ID",
    "DiagnosticToneVoiceProvider",
    "write_diagnostic_wav",
    "VOICE_REPORT_SCHEMA_V1",
    "VOICE_REQUEST_SCHEMA_V1",
    "VoiceProvider",
    "VoiceSegment",
    "VoiceSynthesisResult",
    "build_voice_segments",
    "estimate_arabic_duration_ms",
    "normalize_arabic_text",
    "split_arabic_narration",
    "validate_voice_request",
    "EpisodeRenderAdapterV2",
    "EpisodeRenderV2Result",
    "RENDER_ADAPTER_V2_REPORT_SCHEMA",
    "render_episode_manifest_v2",
    "LocalVideoRenderAdapter",
    "LocalVideoRenderResult",
    "render_local_video_manifest",
    "build_episode_01_preproduction",
    "EPISODE_RENDER_MANIFEST_V2",
    "TimedScene",
    "build_timed_scene_plan",
    "validate_episode_render_manifest_v2",
]
