"""Compatibility facade for the series-wide V2 production controller."""

from src.application.episode_production_control_v2 import (
    ANIMATED_STILL_SHOT_COUNT,
    EDITORIAL_SHOT_COUNT,
    GRAPHICS_SHOT_COUNT,
    HARD_CAP_USD,
    PASS_THRESHOLD,
    TARGET_SPEND_USD,
    VIDEO_PLANNED_SECONDS,
    VIDEO_SHOT_COUNT,
    VIDEO_TARGET_MAX_SECONDS,
    VIDEO_TARGET_MIN_SECONDS,
    BudgetSnapshot,
    EpisodeProductionPolicyError,
    EpisodeProgress,
    assert_budget_allows_new_paid_request,
    episode_progress,
    load_episode_plan,
    load_episode_policy,
    queue_rows,
    scan_actual_paid_spend,
)

__all__ = [
    "HARD_CAP_USD",
    "TARGET_SPEND_USD",
    "VIDEO_TARGET_MIN_SECONDS",
    "VIDEO_TARGET_MAX_SECONDS",
    "VIDEO_PLANNED_SECONDS",
    "VIDEO_SHOT_COUNT",
    "ANIMATED_STILL_SHOT_COUNT",
    "GRAPHICS_SHOT_COUNT",
    "EDITORIAL_SHOT_COUNT",
    "PASS_THRESHOLD",
    "EpisodeProductionPolicyError",
    "BudgetSnapshot",
    "EpisodeProgress",
    "load_episode_policy",
    "load_episode_plan",
    "scan_actual_paid_spend",
    "assert_budget_allows_new_paid_request",
    "episode_progress",
    "queue_rows",
]
